[package]
name = "xswarm-mcp-server"
version = "0.1.0"
edition = "2021"
authors = ["xSwarm Contributors"]
description = "Model Context Protocol isolation server for xSwarm"
license = "MIT"

[[bin]]
name = "xswarm-mcp-server"
path = "src/main.rs"

[dependencies]
# Workspace dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Web server
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["fs"] }

# MCP
tokio-util = { version = "0.7", features = ["codec"] }
