[package]
name = "xswarm-indexer"
version = "0.1.0"
edition = "2021"
authors = ["xSwarm Contributors"]
description = "Semantic search indexer for xSwarm using Meilisearch and Docling"
license = "MIT"

[lib]
name = "xswarm_indexer"
path = "src/lib.rs"

[dependencies]
# Workspace dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

# HTTP client
reqwest = { version = "0.11", features = ["json"] }
