[package]
name = "xswarm-indexer"
version = "0.1.0"
edition = "2021"
authors = ["xSwarm Contributors"]
description = "Semantic search indexer for xSwarm using Meilisearch and Docling"
license = "MIT"

[lib]
name = "xswarm_indexer"
path = "src/lib.rs"

[dependencies]
# Workspace dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# Meilisearch client
meilisearch-sdk = "0.30"

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Local embeddings
fastembed = { version = "3.0", optional = true }

# Code parsing
tree-sitter = { version = "0.20", optional = true }
tree-sitter-rust = { version = "0.20", optional = true }
tree-sitter-typescript = { version = "0.20", optional = true }
tree-sitter-python = { version = "0.20", optional = true }

# File watching
notify = { version = "6.0", optional = true }

# UUID generation
uuid = { version = "1.6", features = ["v4", "serde"] }

# Datetime
chrono = { version = "0.4", features = ["serde"] }

# Async trait
async-trait = "0.1"

[features]
default = ["code-parsing", "file-watching"]
local-embeddings = ["fastembed"]
code-parsing = ["tree-sitter", "tree-sitter-rust", "tree-sitter-typescript", "tree-sitter-python"]
file-watching = ["notify"]
